#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex heterogeneous.tex && latex heterogeneous.tex &&  latex heterogeneous.tex && bibtex heterogeneous && latex heterogeneous.tex && latex heterogeneous.tex && latex heterogeneous.tex && echo "-----------------------------" && dvips heterogeneous.dvi -o && ps2pdf heterogeneous.ps && echo " "
