#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex made.tex && latex made.tex &&  latex made.tex && bibtex made && latex made.tex && latex made.tex && latex made.tex && echo "-----------------------------" && dvips made.dvi -o && ps2pdf made.ps && echo " "
