#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex botants.tex && latex botants.tex &&  latex botants.tex && bibtex botants && latex botants.tex && latex botants.tex && latex botants.tex && echo "-----------------------------" && dvips botants.dvi -o && ps2pdf botants.ps && echo " "
