library("fitdistrplus")
noise.generacion50.01 <- read.table('generacion50/01')
fit.weibull.generacion50.01 <- fitdist( noise.generacion50.01$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.01$estimate,  '\n')
fit.norm.generacion50.01 <- fitdist( noise.generacion50.01$V1, 'norm')
cat('norm ', fit.norm.generacion50.01$estimate,  '\n')
fit.gamma.generacion50.01 <- fitdist( noise.generacion50.01$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.01$estimate,  '\n')
gof.generacion50.01 <- gofstat( list(fit.weibull.generacion50.01, fit.norm.generacion50.01, fit.gamma.generacion50.01),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.01$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.01$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.01$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.01$estimate, '\n')
noise.generacion50.02 <- read.table('generacion50/02')
fit.weibull.generacion50.02 <- fitdist( noise.generacion50.02$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.02$estimate,  '\n')
fit.norm.generacion50.02 <- fitdist( noise.generacion50.02$V1, 'norm')
cat('norm ', fit.norm.generacion50.02$estimate,  '\n')
fit.gamma.generacion50.02 <- fitdist( noise.generacion50.02$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.02$estimate,  '\n')
gof.generacion50.02 <- gofstat( list(fit.weibull.generacion50.02, fit.norm.generacion50.02, fit.gamma.generacion50.02),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.02$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.02$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.02$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.02$estimate, '\n')
noise.generacion50.03 <- read.table('generacion50/03')
fit.weibull.generacion50.03 <- fitdist( noise.generacion50.03$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.03$estimate,  '\n')
fit.norm.generacion50.03 <- fitdist( noise.generacion50.03$V1, 'norm')
cat('norm ', fit.norm.generacion50.03$estimate,  '\n')
fit.gamma.generacion50.03 <- fitdist( noise.generacion50.03$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.03$estimate,  '\n')
gof.generacion50.03 <- gofstat( list(fit.weibull.generacion50.03, fit.norm.generacion50.03, fit.gamma.generacion50.03),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.03$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.03$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.03$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.03$estimate, '\n')
noise.generacion50.04 <- read.table('generacion50/04')
fit.weibull.generacion50.04 <- fitdist( noise.generacion50.04$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.04$estimate,  '\n')
fit.norm.generacion50.04 <- fitdist( noise.generacion50.04$V1, 'norm')
cat('norm ', fit.norm.generacion50.04$estimate,  '\n')
fit.gamma.generacion50.04 <- fitdist( noise.generacion50.04$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.04$estimate,  '\n')
gof.generacion50.04 <- gofstat( list(fit.weibull.generacion50.04, fit.norm.generacion50.04, fit.gamma.generacion50.04),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.04$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.04$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.04$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.04$estimate, '\n')
noise.generacion50.05 <- read.table('generacion50/05')
fit.weibull.generacion50.05 <- fitdist( noise.generacion50.05$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.05$estimate,  '\n')
fit.norm.generacion50.05 <- fitdist( noise.generacion50.05$V1, 'norm')
cat('norm ', fit.norm.generacion50.05$estimate,  '\n')
fit.gamma.generacion50.05 <- fitdist( noise.generacion50.05$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.05$estimate,  '\n')
gof.generacion50.05 <- gofstat( list(fit.weibull.generacion50.05, fit.norm.generacion50.05, fit.gamma.generacion50.05),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.05$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.05$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.05$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.05$estimate, '\n')
noise.generacion50.06 <- read.table('generacion50/06')
fit.weibull.generacion50.06 <- fitdist( noise.generacion50.06$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.06$estimate,  '\n')
fit.norm.generacion50.06 <- fitdist( noise.generacion50.06$V1, 'norm')
cat('norm ', fit.norm.generacion50.06$estimate,  '\n')
fit.gamma.generacion50.06 <- fitdist( noise.generacion50.06$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.06$estimate,  '\n')
gof.generacion50.06 <- gofstat( list(fit.weibull.generacion50.06, fit.norm.generacion50.06, fit.gamma.generacion50.06),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.06$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.06$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.06$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.06$estimate, '\n')
noise.generacion50.07 <- read.table('generacion50/07')
fit.weibull.generacion50.07 <- fitdist( noise.generacion50.07$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.07$estimate,  '\n')
fit.norm.generacion50.07 <- fitdist( noise.generacion50.07$V1, 'norm')
cat('norm ', fit.norm.generacion50.07$estimate,  '\n')
fit.gamma.generacion50.07 <- fitdist( noise.generacion50.07$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.07$estimate,  '\n')
gof.generacion50.07 <- gofstat( list(fit.weibull.generacion50.07, fit.norm.generacion50.07, fit.gamma.generacion50.07),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.07$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.07$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.07$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.07$estimate, '\n')
noise.generacion50.08 <- read.table('generacion50/08')
fit.weibull.generacion50.08 <- fitdist( noise.generacion50.08$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.08$estimate,  '\n')
fit.norm.generacion50.08 <- fitdist( noise.generacion50.08$V1, 'norm')
cat('norm ', fit.norm.generacion50.08$estimate,  '\n')
fit.gamma.generacion50.08 <- fitdist( noise.generacion50.08$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.08$estimate,  '\n')
gof.generacion50.08 <- gofstat( list(fit.weibull.generacion50.08, fit.norm.generacion50.08, fit.gamma.generacion50.08),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.08$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.08$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.08$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.08$estimate, '\n')
noise.generacion50.09 <- read.table('generacion50/09')
fit.weibull.generacion50.09 <- fitdist( noise.generacion50.09$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.09$estimate,  '\n')
fit.norm.generacion50.09 <- fitdist( noise.generacion50.09$V1, 'norm')
cat('norm ', fit.norm.generacion50.09$estimate,  '\n')
fit.gamma.generacion50.09 <- fitdist( noise.generacion50.09$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.09$estimate,  '\n')
gof.generacion50.09 <- gofstat( list(fit.weibull.generacion50.09, fit.norm.generacion50.09, fit.gamma.generacion50.09),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.09$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.09$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.09$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.09$estimate, '\n')
noise.generacion50.10 <- read.table('generacion50/10')
fit.weibull.generacion50.10 <- fitdist( noise.generacion50.10$V1, 'weibull')
cat('weibull ', fit.weibull.generacion50.10$estimate,  '\n')
fit.norm.generacion50.10 <- fitdist( noise.generacion50.10$V1, 'norm')
cat('norm ', fit.norm.generacion50.10$estimate,  '\n')
fit.gamma.generacion50.10 <- fitdist( noise.generacion50.10$V1, 'gamma')
cat('gamma ', fit.gamma.generacion50.10$estimate,  '\n')
gof.generacion50.10 <- gofstat( list(fit.weibull.generacion50.10, fit.norm.generacion50.10, fit.gamma.generacion50.10),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion50.10$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion50.10$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion50.10$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion50.10$estimate, '\n')
noise.generacion1.01 <- read.table('generacion1/01')
fit.weibull.generacion1.01 <- fitdist( noise.generacion1.01$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.01$estimate,  '\n')
fit.norm.generacion1.01 <- fitdist( noise.generacion1.01$V1, 'norm')
cat('norm ', fit.norm.generacion1.01$estimate,  '\n')
fit.gamma.generacion1.01 <- fitdist( noise.generacion1.01$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.01$estimate,  '\n')
gof.generacion1.01 <- gofstat( list(fit.weibull.generacion1.01, fit.norm.generacion1.01, fit.gamma.generacion1.01),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.01$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.01$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.01$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.01$estimate, '\n')
noise.generacion1.02 <- read.table('generacion1/02')
fit.weibull.generacion1.02 <- fitdist( noise.generacion1.02$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.02$estimate,  '\n')
fit.norm.generacion1.02 <- fitdist( noise.generacion1.02$V1, 'norm')
cat('norm ', fit.norm.generacion1.02$estimate,  '\n')
fit.gamma.generacion1.02 <- fitdist( noise.generacion1.02$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.02$estimate,  '\n')
gof.generacion1.02 <- gofstat( list(fit.weibull.generacion1.02, fit.norm.generacion1.02, fit.gamma.generacion1.02),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.02$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.02$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.02$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.02$estimate, '\n')
noise.generacion1.03 <- read.table('generacion1/03')
fit.weibull.generacion1.03 <- fitdist( noise.generacion1.03$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.03$estimate,  '\n')
fit.norm.generacion1.03 <- fitdist( noise.generacion1.03$V1, 'norm')
cat('norm ', fit.norm.generacion1.03$estimate,  '\n')
fit.gamma.generacion1.03 <- fitdist( noise.generacion1.03$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.03$estimate,  '\n')
gof.generacion1.03 <- gofstat( list(fit.weibull.generacion1.03, fit.norm.generacion1.03, fit.gamma.generacion1.03),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.03$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.03$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.03$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.03$estimate, '\n')
noise.generacion1.04 <- read.table('generacion1/04')
fit.weibull.generacion1.04 <- fitdist( noise.generacion1.04$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.04$estimate,  '\n')
fit.norm.generacion1.04 <- fitdist( noise.generacion1.04$V1, 'norm')
cat('norm ', fit.norm.generacion1.04$estimate,  '\n')
fit.gamma.generacion1.04 <- fitdist( noise.generacion1.04$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.04$estimate,  '\n')
gof.generacion1.04 <- gofstat( list(fit.weibull.generacion1.04, fit.norm.generacion1.04, fit.gamma.generacion1.04),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.04$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.04$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.04$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.04$estimate, '\n')
noise.generacion1.05 <- read.table('generacion1/05')
fit.weibull.generacion1.05 <- fitdist( noise.generacion1.05$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.05$estimate,  '\n')
fit.norm.generacion1.05 <- fitdist( noise.generacion1.05$V1, 'norm')
cat('norm ', fit.norm.generacion1.05$estimate,  '\n')
fit.gamma.generacion1.05 <- fitdist( noise.generacion1.05$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.05$estimate,  '\n')
gof.generacion1.05 <- gofstat( list(fit.weibull.generacion1.05, fit.norm.generacion1.05, fit.gamma.generacion1.05),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.05$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.05$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.05$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.05$estimate, '\n')
noise.generacion1.06 <- read.table('generacion1/06')
fit.weibull.generacion1.06 <- fitdist( noise.generacion1.06$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.06$estimate,  '\n')
fit.norm.generacion1.06 <- fitdist( noise.generacion1.06$V1, 'norm')
cat('norm ', fit.norm.generacion1.06$estimate,  '\n')
fit.gamma.generacion1.06 <- fitdist( noise.generacion1.06$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.06$estimate,  '\n')
gof.generacion1.06 <- gofstat( list(fit.weibull.generacion1.06, fit.norm.generacion1.06, fit.gamma.generacion1.06),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.06$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.06$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.06$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.06$estimate, '\n')
noise.generacion1.07 <- read.table('generacion1/07')
fit.weibull.generacion1.07 <- fitdist( noise.generacion1.07$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.07$estimate,  '\n')
fit.norm.generacion1.07 <- fitdist( noise.generacion1.07$V1, 'norm')
cat('norm ', fit.norm.generacion1.07$estimate,  '\n')
fit.gamma.generacion1.07 <- fitdist( noise.generacion1.07$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.07$estimate,  '\n')
gof.generacion1.07 <- gofstat( list(fit.weibull.generacion1.07, fit.norm.generacion1.07, fit.gamma.generacion1.07),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.07$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.07$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.07$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.07$estimate, '\n')
noise.generacion1.08 <- read.table('generacion1/08')
fit.weibull.generacion1.08 <- fitdist( noise.generacion1.08$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.08$estimate,  '\n')
fit.norm.generacion1.08 <- fitdist( noise.generacion1.08$V1, 'norm')
cat('norm ', fit.norm.generacion1.08$estimate,  '\n')
fit.gamma.generacion1.08 <- fitdist( noise.generacion1.08$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.08$estimate,  '\n')
gof.generacion1.08 <- gofstat( list(fit.weibull.generacion1.08, fit.norm.generacion1.08, fit.gamma.generacion1.08),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.08$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.08$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.08$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.08$estimate, '\n')
noise.generacion1.09 <- read.table('generacion1/09')
fit.weibull.generacion1.09 <- fitdist( noise.generacion1.09$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.09$estimate,  '\n')
fit.norm.generacion1.09 <- fitdist( noise.generacion1.09$V1, 'norm')
cat('norm ', fit.norm.generacion1.09$estimate,  '\n')
fit.gamma.generacion1.09 <- fitdist( noise.generacion1.09$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.09$estimate,  '\n')
gof.generacion1.09 <- gofstat( list(fit.weibull.generacion1.09, fit.norm.generacion1.09, fit.gamma.generacion1.09),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.09$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.09$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.09$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.09$estimate, '\n')
noise.generacion1.10 <- read.table('generacion1/10')
fit.weibull.generacion1.10 <- fitdist( noise.generacion1.10$V1, 'weibull')
cat('weibull ', fit.weibull.generacion1.10$estimate,  '\n')
fit.norm.generacion1.10 <- fitdist( noise.generacion1.10$V1, 'norm')
cat('norm ', fit.norm.generacion1.10$estimate,  '\n')
fit.gamma.generacion1.10 <- fitdist( noise.generacion1.10$V1, 'gamma')
cat('gamma ', fit.gamma.generacion1.10$estimate,  '\n')
gof.generacion1.10 <- gofstat( list(fit.weibull.generacion1.10, fit.norm.generacion1.10, fit.gamma.generacion1.10),fitnames=c("weibull", "norm", "gamma"))
cat( 'Fit  AIC ', gof.generacion1.10$aic, '\n')
cat( 'Fit  Chi^2 p value', gof.generacion1.10$chisqpvalue, '\n')
cat( 'Fit  Chi^2', gof.generacion1.10$chisq, '\n')
cat( 'Gamma params', fit.gamma.generacion1.10$estimate, '\n')
flush.console()
