#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex soahetero.tex && latex soahetero.tex &&  latex soahetero.tex && bibtex soahetero && latex soahetero.tex && latex soahetero.tex && latex soahetero.tex && echo "-----------------------------" && dvips soahetero.dvi -o && ps2pdf soahetero.ps && echo " "
