#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex multikulti-evostar.tex && latex multikulti-evostar.tex &&  latex multikulti-evostar.tex && bibtex multikulti-evostar && latex multikulti-evostar.tex && latex multikulti-evostar.tex && latex multikulti-evostar.tex && echo "-----------------------------" && dvips multikulti-evostar.dvi -o && ps2pdf multikulti-evostar.ps && echo " "
