#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex osgiliath.tex && latex osgiliath.tex &&  latex osgiliath.tex && bibtex osgiliath && latex osgiliath.tex && latex osgiliath.tex && latex osgiliath.tex && echo "-----------------------------" && dvips osgiliath.dvi -o && ps2pdf osgiliath.ps && echo " "
