#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex gpbot_fitness.tex && latex gpbot_fitness.tex &&  latex gpbot_fitness.tex 
#bibtex paper
#latex paper.tex && latex paper.tex && latex paper.tex

echo "-----------------------------" 

dvips gpbot_fitness.dvi -o && ps2pdf gpbot_fitness.ps

rm *.ps

echo "-----------------------------"
