#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex soa-atc.tex && latex soa-atc.tex &&  latex soa-atc.tex && bibtex soa-atc && latex soa-atc.tex && latex soa-atc.tex && latex soa-atc.tex && echo "-----------------------------" && dvips soa-atc.dvi -o && ps2pdf soa-atc.ps && echo " "
