#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex gpbot.tex && latex gpbot.tex &&  latex gpbot.tex && bibtex gpbot && latex gpbot.tex && latex gpbot.tex && latex gpbot.tex && echo "-----------------------------" && dvips gpbot.dvi -o && ps2pdf gpbot.ps && echo " "
