#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex evoart.tex && latex evoart.tex &&  latex evoart.tex && bibtex evoart && latex evoart.tex && latex evoart.tex && latex evoart.tex && echo "-----------------------------" && dvips evoart.dvi -t letter -o && ps2pdf evoart.ps && echo " "
