#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex soaea.tex && latex soaea.tex &&  latex soaea.tex && bibtex soaea && latex soaea.tex && latex soaea.tex && latex soaea.tex && echo "-----------------------------" && dvips soaea.dvi -o && ps2pdf soaea.ps && echo " "
