#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

latex osgi-evosoft.tex && latex osgi-evosoft.tex &&  latex osgi-evosoft.tex && bibtex osgi-evosoft && latex osgi-evosoft.tex && latex osgi-evosoft.tex && latex osgi-evosoft.tex && echo "-----------------------------" && dvips osgi-evosoft.dvi -o && ps2pdf osgi-evosoft.ps && echo " "
