#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

pdflatex made.tex && pdflatex made.tex &&  pdflatex made.tex && bibtex made && pdflatex made.tex && pdflatex made.tex && pdflatex made.tex && echo "-----------------------------" && echo " "
