#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi

pdflatex pap662-garcía-ortega.tex && pdflatex pap662-garcía-ortega.tex &&  pdflatex pap662-garcía-ortega.tex && bibtex pap662-garcía-ortega && pdflatex pap662-garcía-ortega.tex && pdflatex pap662-garcía-ortega.tex && pdflatex pap662-garcía-ortega.tex && echo "-----------------------------" && echo " "
